const String MORNING = "Morning";
const String AFTERNOON = "Afternoon";
const String EVENING = "Evening";
const String NIGHT = "Night";

const int MORNING_START_HOUR = 8;
const int MORNING_END_HOUR = 12;
const int AFTERNOON_END_HOUR = 17;
const int EVENING_END_HOUR = 19;
const List<String> TIME_IN_ORDER = [MORNING, AFTERNOON, EVENING, NIGHT];
const List<int> TIME_OFFSET = [
  MORNING_END_HOUR - MORNING_START_HOUR,
  AFTERNOON_END_HOUR - MORNING_END_HOUR,
  EVENING_END_HOUR - AFTERNOON_END_HOUR,
  EVENING_END_HOUR - MORNING_START_HOUR,
];

const int DEFAULT_ALARM_ID = 0;

const MORNING_ALARM_ID = 0;
const AFTERNOON_ALARM_ID = 1;
const EVENING_ALARM_ID = 2;
const NIGHT_ALARM_ID = 3;